### ISSUE TITLE
Summary of libp2p gossipsub issues

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#1161]
ETA: 2022Q4

all in the context of gossipsub:
* we want nodes in the "core network" to automatically retry connections to a set of initial peering nodes. If they don't, a single node (or several) restarting, or even just a dropped TCP connection can "explode" the network into disconnected subsets!
* we had previously called:
```
		t.host.Peerstore().AddAddrs(info.ID, info.Addrs, peerstore.PermanentAddrTTL)
		err = t.host.Connect(ctx, *info)
```
just at startup, but this didn't reconnect
* we tried switching to
```
		pubsub.WithDirectPeers(pis),
		pubsub.WithDirectConnectTicks(10),
```
which had the desired effect that the direct peering nodes would reconnect automatically, but this caused very high message latencies (800ms+) and out of order message delivery, even on devstack (3 nodes on localhost)
* on a global network with 5 nodes in Europe and 5 nodes in USA it was unusable
* however, in that configuration we didn't have the DirectPeers be _reciprocal_, which from reading the code looks like it might have been important
* in #1154, we reverted the `WithDirectPeers` change and instead just started calling `Connect` every 10 seconds. This fixed our CI which had been suffering from the high latency and out of order message delivery as well (many of our tests run in-process libp2p)
* this will probably keep us going for a while but would love to pair with a libp2p/gossipsub expert to better understand what's going on and what we should ideally be doing
* my instinct is that we want a "backbone" of DirectPeer nodes in a similar geography and the rest of the network connects ad-hoc to that, so that most message delivery doesn't have to e.g. cross the Atlantic multiple times
* going to deploy #1154 soon and see how it performs in practice

**Comment by daviddias** [comment]
Hi folks! I had a good back and forth with @aronchick in slack and a few things popped up.

- Gossipsub is not designed for small networks. Gossipsub is ultimately a protocol designed to tradeoff latency for bandwidth efficiency for large networks, while preventing multiple attacks.
- Gossipsub by default, assumes that what you want is a geodistributed healthy network. If you have 10 nodes within two datacenters (two ip ranges) it will start prunning itself out
- Also see the parameters, you likely need to adjust there for your usecase https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#the-score-function
- I believe what you want is to use FloodSub for now until you scale it up. The reason why we broke the PubSub abstraction (API) from the implementation, is so that we could have apps that have their needs evolve without having to be reprogrammed by having them just switch the module that fits them bestl.

Fortunately, Gossipsub is probably one of the best (if not the best) well documented protocols. Did you had a chance to watch/read:
- The talk https://youtu.be/APVp-20ATLk?t=4689
- The paper https://arxiv.org/pdf/2007.02754.pdf
- The evaluation https://research.protocol.ai/publications/gossipsub-v1.1-evaluation-report/vyzovitis2020.pdf
- The spec https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md

Also, totally worth setting up office ours with @vyzo to discuss the challenges you are facing

**Comment by lukemarsden** [comment]
Thank you David!

**Comment by iand** [comment]
@daviddias @vyzo note that Bacalhau already uses the WithFloodPublish and WithPeerExchange options (see https://github.com/filecoin-project/bacalhau/blob/main/pkg/transport/libp2p/libp2p.go#L117).

Would it be better to use autorelay similar to how the gateways have fixed peering? (i.e. [autorelay.WithPeerSource](https://pkg.go.dev/github.com/libp2p/go-libp2p/p2p/host/autorelay#WithPeerSource))

**Comment by aronchick** [comment]
Closing as stale
