### ISSUE TITLE
Errors don't explain resource limits

### ISSUE THREAD

**Issue by simonwo** [filecoin-project/bacalhau#1270]
As per https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1668893456894809:

> [Not urgent] Hi all, what is the max memory for docker workflows? Locally my task peaks at using 19gb memory. Posting the same task on Bacalhau causes a 137 error. The same image can run other workflows on Bacalhau that require less memory. 
> The command is `bacalhau docker run --gpu=1 -o output:/code/output openzyme/compbio:a0.2 python workflows/fold-protein.py`
> The other command that does work with the same image is: `bacalhau docker run --gpu=1 -o output:/code/output openzyme/compbio:a0.2 python workflows/simulate-protein.py`
> FYI passing in `--memory=30GB` did the trick to resolve the 137 error. Thanks!

We should explain what is happening when the required memory is over the limit and also document the defaults.

**Comment by wjam** [comment]
It's not easy to identify when the OOM killer has killed a process within your container, as it may not be the primary one which was terminated.

Do we show the default limits when reading the job spec back? I would expect the defaults to be applied as the job is saved so that the user can see what defaults have been applied.

**Comment by aronchick** [comment]
Closing as stale
