### ISSUE TITLE
Need a way to identify submitting user

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#253]
We need to identify what user submitted a job in some unique way, so that in the future they can query based on that.

**Comment by lukemarsden** [comment]
how are we going to stop malicious clients impersonating random users on the network? will we require that REST API calls are signed, so that everyone can verify that only they could have that public identity?

**Comment by lukemarsden** [comment]
oh, cool, that is exactly what @Bubblyworld is doing in https://github.com/filecoin-project/bacalhau/pull/315 :+1:

**Comment by Bubblyworld** [comment]
@lukemarsden Yeah, a user's identity is going to be defined by their configured keypair 👌 one interesting problem is how the client is going to share their public key with the server so that the signature can be verified. Probably the easiest option for now is just attaching it to each API call, don't think it's going to be a big bottleneck.

**Comment by Bubblyworld** [comment]
Libp2p automatically signs messages in the gossip network right? So once we're passed the api server boundary then message authenticity shouldn't be a problem.

**Comment by lukemarsden** [comment]
Sounds right to me

**Comment by Bubblyworld** [comment]
Last thing is that currently `system/config.go` only supports RSA keys, but we can support ECDSA keypairs fairly easily if we want to. I've left a detailed TODO for it in the code. Generally I'd guess that users will just use the autogenerated key, so it shouldn't be a big deal for now.
