### ISSUE TITLE
Span everything and add some basic queries to honeycomb.

### ISSUE THREAD

**Issue by Bubblyworld** [filecoin-project/bacalhau#262]
OTEL integration is working now, and I can confirm that the issues we were seeing before were rate limiting on honeycomb's side. An example of a complete trace from `devstack_test.go`:

<img width="1248" alt="Screenshot 2022-06-19 at 14 01 03" src="https://user-images.githubusercontent.com/6214591/174479878-31104739-13b6-4a1f-9313-65265bc7215c.png">

From dave:
<img width="742" alt="Screenshot 2022-06-19 at 14 01 34" src="https://user-images.githubusercontent.com/6214591/174479907-42eca8b5-308a-4edc-9f4b-84003bf14cd5.png">

**Comment by aronchick** [comment]
FWIW, here's some milestones that we have in our backlog - let's start by just targeting some of these measurements - 

1. *(basic)* Build a system for unreliably running a single deterministic program where a single 10MB piece of data is on IPFS, assuming everyone participating is trustworthy, assuming only 10 nodes in the network.*Example:* Run cloud detection on a single Landsat image file. Get the result back. Verify it by eye.

**JUNE**

1. ***(reliability)* Extend that system to work 99% of the time. Submit 10,000 jobs and show that at most 100 of them fail. It might take several minutes to resolve each job.**
    1. **Example:** By the end of this phase, job execution will be significantly more reliable. We’ll generally be able to submit 50 jobs and have them all succeed.
    2. **Status:** Just underway, most important work will be supporting non-hosted storage
2. *(scale-1)* Extend that system to work when 100 nodes and have access to 100TB of data. Still, the error rate might be high.
    1. **Example:** 90 more nodes join the network and at first things break, but by the end of the milestone the network is working well again, albeit slowly and with some error rate

**JULY**

1. *(multi-file)* Extend that system to work when jobs consist of many (thousands) of files, rather than a single file, and we want to distribute the work across the network and run it in parallel.
    1. **Example:** A user can submit a cloud detection on 10,000 Landsat images at once and have the work be parallelised automatically on the network, still according to data locality where possible.
2. *(scale-2)* Extend the system to work when 1000 nodes are participating, over 1PB of data. Resolving jobs now may take a very long time (10s of minutes).
    1. **Example:** Many users can run landsat data in parallel, along with use cases on public biomedical images and 9 other use cases without the network failing.

**AUGUST**

1. *(performance-1)* Get the resolution of jobs down to seconds, even in large networks where 1000s of nodes are participating with hundreds of job submissions per second.
    1. **Example:** As the network is dealing with a multitude of use cases (landsat, biomedical, SETI@home and protein folding has migrated over to use Bacalhau, etc) and the network is processing hundreds of job executions per second, it’s now started to slow down a lot. This phase is all about getting it speedy again.
2. *(byzantine-1)* Extend that system to work when up to 10% of the nodes are malicious.
    1. **Example:** Even when a small minority of nodes are trying to mess up the results, a user can still run cloud detection on 10,000 files in IPFS with no errors or incorrect results.

**Comment by Bubblyworld** [comment]
Right, yeah, that's a really good set of use-cases 🙏 and just a note for future user testing:

```
Add tracing such that we can see how people start the job (eg using CLI flags or a yaml file (when available))
```

**Comment by Bubblyworld** [comment]
And more notes:

```
Ah, sweet :ok_hand: we should get a HONEYCOMB_KEY in there soon so we can see prod traces



New


[Luke Marsden](https://app.slack.com/team/U02MVNLKDUG)
  [1 minute ago](https://filecoinproject.slack.com/archives/C039T4V20NP/p1655738154367069?thread_ts=1655737650.170719&cid=C039T4V20NP)
ooh yes please! for now we can just write secrets manually to a .env file on the production machines’ persistent data drives, and source that in the cloud-init startup script
```
