### ISSUE TITLE
Every node should be able to coordinate with every other node (no jrpcports or jrpcservers necessary)

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#38]

**Comment by lukemarsden** [comment]
We probably need to have a diagram of the current architecture, because the jsonrpc is ONLY for the CLI (not a long-running server) to communicate with the local node to ask it to coordinate work on its behalf. Everything else is currently proper libp2p gossipsub.

Does that help, or was this issue about something else?
