### ISSUE TITLE
fix test flakiness when running multiple wasm tests

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#382]
ETA: 2023Q1

Something about the wasm tests breaks when you run more than one of them _in the same test run_.

This is terrible and bad and I skipped two of them because I was in a hurry.

This issue is for un-skipping them, and figuring out why they are failing when you run more than one of them in the same run. Something to do with IPFS cleanup in-process?

**Comment by wdbaruni** [comment]
Is this still an issue? cc: @lukemarsden @simonwo

**Comment by simonwo** [comment]
I suspect we are talking about the Python WASM tests in this issue, which are quite separate from the native WASM tests (they use a different executor). This shouldn't be true of the native WASM tests, but might still be true of the Python tests. To be investigated!

**Comment by wjam** [comment]
Currently attempting to solve this. The root of the problem is in how corba is being configured.

**Comment by wjam** [comment]
Reasons why the tests are currently broken, in the order needed to be fixed:

1. Use of globals around the cobra command stuff. These will need to be changed to functions, so that each test can get a fresh state.
2. Dummy input volume is added the job if none is defined. This will cause IPFS to fail as it can't find the dummy input volume
3. The tests assume the output only contains the job ID
4. Some commands are failing even from the command line. We think it's because they lack any inputs?
