### ISSUE TITLE
Incorrect state on finished job

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#539]
- Start devstack
- Go to new window
- Run:
```bash
go run . docker run ubuntu echo "hello world"
go run . list
```

Expected:
```
 CREATION_TIME  ID        JOB                      STATE      RESULT
 15:01:00       d7d4d23d  Docker ubuntu echo h...  Completed  /ipfs/QmW7TdjNEMzqmW...
```

Actual:
```
 CREATION_TIME  ID        JOB                      STATE      RESULT
 15:01:00       d7d4d23d  Docker ubuntu echo h...  Published  /ipfs/QmW7TdjNEMzqmW...
```

**Comment by lukemarsden** [comment]
Completed is probably a better word than Published. How about Finished?

Submitted
Running
Error
Completed
Published

--> 

FinishedRunning
CompletedPublished or something?

Or Completed and Finalized?

**Comment by lukemarsden** [comment]
Executed
Verifying
Completed

help could say "to learn more about the states you go through click here to go to our docs"

**Comment by binocarlos** [comment]
`Executed` makes sense for "I have finished running the compute job" but really that is `Verifying` because as soon as the shard has finished running - it's technicaly in "I am now being verified" mode

So I think it's:

 * `Running` = I am still running CPU cycles
 * `Verifying` = I have finished running CPU cycles but don't know if my results will be accepted yet
 * `Publishing` = I have heard back about the verification and so am now publishing the results
 * `Completed` = I have finished publishing the results

**Comment by lukemarsden** [comment]
cool now the issue is just doing some renaming :)

**Comment by lukemarsden** [comment]
@enricorotundo could you pick up the renaming in due course please?

**Comment by enricorotundo** [comment]
Renamed in https://github.com/filecoin-project/bacalhau/pull/587

However, the `Publishing` is not even implemented.
