### ISSUE TITLE
Make list work well

### ISSUE THREAD

**Issue by enricorotundo** [filecoin-project/bacalhau#611]
**Update:** New task list (from comment below):

- [x] It's slow because it does lots of requests (it should be O(1) not O(N)) - https://github.com/filecoin-project/bacalhau/issues/520
- [x] Server-side query response with only the data that's needed and that's already sorted (i.e. only jobs labelled with user's public key)
- [x] Add `--all` flag to return all jobs available
- [x] Move "resolve job details" routine to server side
- [ ] Make sure that all existing flags still work (add new tests, if missing)
   - [x] --all (new!) 
   - [x] --hide-header
   - [x] --no-style
   - [x] --wide 
   - [x] --output
   - [x] --reverse
   - [x] --sort-by
- [x] Make sure short-id works
- [x] ~Remove client code that does pagination and move it to the server~ Update: there was no pagination code actually
- [x] Fix `list --id-filter --output json` does NOT filter + tests
- [x] `Get` also needs a fix - https://github.com/filecoin-project/bacalhau/issues/452
- [x] Fix `describe` too
- [x] Fix existing tests (done in https://github.com/filecoin-project/bacalhau/pull/678)
- [ ] Add more tests!!!
- [ ] ~Change List options to Functional Options~

**Comment by lukemarsden** [comment]
Maybe we can address all of these in one go; we should make list work well:
- [ ] Server side query response with only the data that's needed that's already sorted
- [ ] Remove client code that does pagination and move it to the server
- [ ] It's slow because it does lots of requests
- [ ] Make sure that all existing flags still work

**Comment by wdbaruni** [comment]
what is the user expectation from a list, assuming no filters were passed? Is it listing all the jobs in the network since the beginning of time? If an explicit or an implicit `limit` was set, do we support pagination with continuation tokens? Do all Bacalhau nodes need to be aware of the jobs submitted to the network along with their state?

I mainly want to understand the use case and how we plan to scale `list` and the job state

**Comment by enricorotundo** [comment]
@wdbaruni has a good point and I'd like to take it further. 

It's a public network, and while we still need to be able to list *all* jobs in some way, I question whether we want to expose all that to users. The point is, if the number of entries in `list` is large, wouldn't you'll be interested only in a sub-set of that? Your scope may be your own work, project, organization, whatever, maybe we can come up with a number of possible hierarchies.

**Comment by lukemarsden** [comment]
If we label the job with a hash of the the client's public key, we could
default to only showing you your own jobs, with a flag for showing all
jobs. If we do that filtering on the server side, list would get nice and
quick for most users most of the time, which would be a big win.

**Comment by wdbaruni** [comment]
I like Luke's proposal as it will allow scaling the state the network needs to maintain without having each node keep a copy of every single job state. 

To handle `describe/get` we can use a DHT where the key is the jobId and the value is the job state. To handle `list` we can also use another DHT where the value is the client public key and the value is a list of jobIds along with a state summary. The problem here is we can still run into hot partitions for the clients that submit a lot of jobs. There can be multiple mitigations here, but if the goal of `list` is to just return the latest `n` jobs or the jobs that were submitted in the last `t` time, then this can simplify things a little, specially that we now have rate limiting enabled
