### ISSUE TITLE
[is-it-a-bug] The IPFS artefact containing the output data always adds an `./outputs/` directory

### ISSUE THREAD

**Issue by philwinder** [filecoin-project/bacalhau#788]
The issue here is that as a user, I expect the IPFS result to contain the contents of the`/outputs` directory. E.g.

If I were to view IPFS CID `123432432432`, then I would expect the directory structure to look like:
```
.
├── foo.txt
└── some-dir
    └── bar.txt
```

But in fact, the structure is:
```
.
└── outputs
    ├── foo.txt
    └── some-dir
        └── bar.txt
```

So for example, when reusing a CID in a subsequent job, I have to look for files inside the `inputs` then `outputs` directory, which very quickly gets confusing. Like this:

`bacalhau docker run --download --inputs Qma5e6EDpPe2TsKuz3tumSPSta6vtx48A18f9k99HJATfp ubuntu -- ls -l /inputs/outputs/`

**Comment by aronchick** [comment]
Huh! Not good - I'll try to find today

**Comment by binocarlos** [comment]
So I think that this needs a bit more thinking because we have the option to have multiple output volumes and so the single "results" cid has to encompass `outputs` (the automatically created output volume) and `data` and `mycustomoutputvolume`

Now - we could say that there is always a single output volume but then that might constrict jobs where containers already will write to multiple locations and we want to capture all of those outputs - for example - if we run some kind of data processing container - it might write files to:

 * `/data`
 * `/logs/thing`
 * `/artifacts`

And now it's really hard to make that container to write all of it's files to the same output location.

Having said that - I can see why the above comment is bad UX - how about we print the CIDs of each output volume as part of the results summary - e.g.:

```
Your job has complete - the CID of the results are:

  * all results: Qma5e6....
  * volumes
    * `outputs`: Qme7b2...
    * `data`: Qmc9d2...
    * `logs`: Qm67e2..
```

This could also be included in the describe output

Then - to directly consume the contents of a single output volume in another job - the user just has to copy the CID of the output volume they want without having to do path munging or ipfs lookups themselves - also we get to keep multiple output volumes which I think is quite important

**Comment by lukemarsden** [comment]
yeah sounds fine, thanks!
