### ISSUE TITLE
[bug] urldownloader doesn't allow url:/some/dir any more

### ISSUE THREAD

**Issue by philwinder** [filecoin-project/bacalhau#866]
Since the cli update there's been a few issues with the URL downloader, which derives from the fact that the only valid way of using it is from file->file. I.e. directory options are not valid.

But the rest of the codebase defaults to passing directories around.

In this case, the old method of `-u https://foo.bar/file.zip:/custom/dir/file.zip` is broken.

Ideally someone would spend some time making this cleaner and more obvious, because there's probably more path handling bugs here.

E.g. failing command:
```
bacalhau docker run --input-urls http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz:/adir/train-images-idx3-ubyte.gz ubuntu -- ls -la /
```
Fails because it literally tries to download `HTTP://foo.bar:/some/dir`. If you remove the `:/foo/bar` section it works (and should continue to work).

**Comment by aronchick** [comment]
I  took this out intentionally - it was not usable in its previous state.

https://foo.com:8000:/mymount
https://foo.com:/mymount2
https://foo.com:8000

these are all valid but impossible (in my mind) to get which is which with out a ton of weird parsing. And we had previously wrote our own URL parser which is a virtual guarantee to bite us later.

I think we should either put everything in /inputs or put everything in its own directory that we give them. Aski by people to name their mount seems like an edge case that we don’t need to tackle right now (yes I have many of the same thoughts about the other volume mounts, but at least those are parseable because colons are not a valid directory character)

**Comment by aronchick** [comment]
Not having a volume mount is a decision i think we should make. Happy to undo, but it makes parsing quite hard.
