### ISSUE TITLE
Issue with submitting a job

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#934]
```
bacalhau docker run \
    --cpu 8 \
    --memory 8Gb \
    --download \
    -v bafybeiejgmdpwlfgo3dzfxfv3cn55qgnxmghyv7vcarqe3onmtzczohwaq:/inputs \
    --workdir /inputs/ \
    davidgasquez/duckdb -- duckdb -s "select count(*) from '0_yellow_taxi_trips.parquet'"
```

Reports 

```
$ bacalhau docker run -v bafybeiejgmdpwlfgo3dzfxfv3cn55qgnxmghyv7vcarqe3onmtzczohwaq:/inputs --workdir /inputs/ davidgasquez/duckdb -- duckdb -s "select count(*) from '0_yellow_taxi_trips.parquet'"
Job successfully submitted. Job ID: 59965081-b371-479b-bf83-b83d7b828f89
Checking job status... (Enter Ctrl+C to exit at any time, your job will continue running):

               Creating job for submission ... done :white_check_mark:
               Finding node(s) for the job ... done :white_check_mark:
                     Node accepted the job ... Error submitting job: Error getting job events: publicapi: after posting request: Job not found. ID: 59965081-b371-479b-bf83-b83d7b828f89 
```

**Comment by binocarlos** [comment]
this is happening because of an apparent disconnect between libp2p nodes and so events were not being seen by nodes and so jobs were unknown (leading to this error)

we have:

 * added an `WithEventTracer` to our libp2p node which logs to a JSON file libp2p internal events #938 
 * activated `WithFloodPublish` which should be pro-actively publishing messages to every node #938
 * increased the number of bootstrap connections from 1 -> 3 (to try to keep more routes open) #944

I'm going to close this issue but we are all keeping an eye on this and if the problem crops up again I will re-open this to track it
